### ISSUE TITLE
All Assets are reporting 404 after fresh installation

### ISSUE THREAD

**Issue by rayyzhong** [craftcms/happy-lager#21]
Env:
Mac
craftcms 3.1.12
php 7.2.15
nginx

After fresh installation, all assets are reporting 404.
e.g. 
http://nnit.test/assets/site/_thumb/diva-cover.jpg

HTTP 404 – Not Found – yii\web\NotFoundHttpException
Page not found.

 ```php

    /**
     * @inheritdoc
     * @internal Based on \yii\web\Request::resolve(), but we don't modify $_GET/$this->_queryParams in the process.
     */
    public function resolve()
    {
        if (($result = Craft::$app->getUrlManager()->parseRequest($this)) === false) {
            throw new NotFoundHttpException(Craft::t('yii', 'Page not found.'));
        }
```

**Comment by rayyzhong** [comment]
Updating assets index doesn't help, while admin functions works fine.

**Comment by christattum** [comment]
I had this issue. Fixed it by setting 'dev' => 'siteUrl' in config/general.php, then updating asset index.

**Comment by LarryBarker** [comment]
@christattum What do you mean by `'dev' => 'siteUrl'`? `dev` is a key in that config file... so surely I'm not replacing what value is there with `siteUrl`? Am I adding a new key `siteUrl` to that part of the config? 

More generally, I'm surprised this is even an issue with a project from Craft.

**Comment by rayyzhong** [comment]
> @christattum What do you mean by `'dev' => 'siteUrl'`? `dev` is a key in that config file... so surely I'm not replacing what value is there with `siteUrl`? Am I adding a new key `siteUrl` to that part of the config?
> 
> More generally, I'm surprised this is even an issue with a project from Craft.

Surprised the keep this opened for years.
