### ISSUE TITLE
Fresh Installation is not working fine

### ISSUE THREAD

**Issue by akanshutambi811** [craftcms/happy-lager#24]
![Capture](https://user-images.githubusercontent.com/50816947/61861331-49c87e00-aee9-11e9-8b56-ef82ed805769.PNG)

Getting issues while i installed fresh setup at my localhost 
I had attached screenshot to see what exactly it happening for web view as well as admin view.

Looking forward for your positive feedback
Thanks
Akanshu

**Comment by angrybrad** [comment]
What's the URL you're on when you get that 404?
