### ISSUE TITLE
Add multiple locales/sites and language switcher

### ISSUE THREAD

**Issue by piotrpog** [craftcms/happy-lager#25]
Handling multiple locales is important feature of Craft, therefore i think it would be good idea to show it off in demo site.

**Comment by timkelty** [comment]
This would also be helpful for reporting bugs and creating reproducible test cases.

**Comment by JayGreentree** [comment]
> Handling multiple locales is important feature of Craft, therefore i think it would be good idea to show it off in demo site.

This is available. under admin > entries > locations
